
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import JSONResponse
from sqlalchemy.orm import Session

from app.api.deps import require_roles
from app.db.session import get_db
from app.models.canonical import CanonicalEvent
from app.models.event import Event
from app.models.evidence import RawEvidence
from app.models.audit import AuditLog
from app.models.replay import ReplayRun
from app.models.attck import ATTACKMapping
from app.models.user import User
from app.services.audit_service import record_audit
from app.services.integrity_service import verify_integrity

router = APIRouter()


@router.get("/event/{event_id}")
def event_report(
    request: Request,
    event_id: str,
    db: Session = Depends(get_db),
    user: User = Depends(require_roles("ADMIN", "ANALYST", "AUDITOR")),
):
    e = db.query(Event).filter(Event.event_id == event_id).first()
    if not e:
        raise HTTPException(status_code=404, detail="Event not found")
    c = db.query(CanonicalEvent).filter(CanonicalEvent.event_id == event_id).first()
    ev = db.query(RawEvidence).filter(RawEvidence.event_id == event_id).first()
    replays = db.query(ReplayRun).filter(ReplayRun.event_id == event_id).all()
    audits = db.query(AuditLog).filter(AuditLog.resource_id == event_id).all()
    attck = db.query(ATTACKMapping).filter(ATTACKMapping.event_id == event_id).all()

    integrity = verify_integrity(db, ev) if ev else None

    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generated_by": user.email,
        "event": {
            "event_id": e.event_id, "ingestion_id": e.ingestion_id,
            "correlation_id": e.correlation_id,
            "ingested_at": e.ingested_at.isoformat(),
            "source": e.source, "source_type": e.source_type,
            "detected_format": e.detected_format,
            "detection_confidence": e.detection_confidence,
            "parser_id": e.parser_id, "parser_version": e.parser_version,
            "processing_status": e.processing_status,
        },
        "evidence": {
            "sha256": ev.sha256 if ev else None,
            "raw_size": ev.raw_size if ev else None,
            "storage_backend": ev.storage_backend if ev else None,
            "storage_location": ev.storage_location if ev else None,
            "integrity": integrity,
        },
        "canonical": {
            "timestamp": c.timestamp.isoformat() if c else None,
            "event_type": c.event_type if c else None,
            "category": c.category if c else None,
            "severity": c.severity if c else None,
            "risk_score": c.risk_score if c else None,
            "risk_factors": c.risk_factors if c else None,
            "validation_status": c.validation_status if c else None,
            "validation_notes": c.validation_notes if c else None,
            "mapping_provenance": c.mapping_provenance if c else None,
            "extensions": c.extensions if c else None,
        },
        "attck": [{
            "technique_id": a.technique_id, "technique_name": a.technique_name,
            "tactic": a.tactic, "confidence": a.confidence, "reason": a.reason,
        } for a in attck],
        "replay_history": [{
            "replay_id": r.replay_id, "operator": r.operator, "result": r.result,
            "previous_status": r.previous_status, "new_status": r.new_status,
            "created_at": r.created_at.isoformat(),
        } for r in replays],
        "audit_trail": [{
            "audit_id": a.audit_id, "timestamp": a.timestamp.isoformat(),
            "actor": a.actor, "action": a.action,
            "integrity_hash": a.integrity_hash,
        } for a in audits],
        "notes": "This report is generated by ULPF. It does not claim legal admissibility.",
    }
    record_audit(db, actor=user.email, action="REPORT_GENERATE", resource="event",
                 resource_id=event_id)
    db.commit()
    return JSONResponse(report)